import type { Meta, StoryObj } from "@storybook/vue3-vite";

// A follow-up to the OEH-45 field-component stories in this directory,
// covering something adjacent but different: the "Case identification" /
// "Recipient" / "Structured name of a person" style group headers seen
// wrapping clusters of fields in the real app (`CompositionForm.vue`).
//
// These ARE generated by medblocks-ui, but not as a separate `mb-*` custom
// element — they're plain `<div>`s that `<mb-auto-form>` builds internally
// (its `traverse()`/`treeChildrenPTag()` logic in the medblocks-ui@0.0.217
// bundle) for every Web Template node with children, using the classes
// `.heading` (the bordered card) and `.p-depth`/`.bg-slate-700`/`-600`/
// `-500`/`-400` (the colored title bar, one shade per nesting depth).
//
// Unlike every field in the other OEH-45 stories, this chrome is IMMUNE to
// `medblocks-overrides.css`: the div tree is built and appended inside
// `<mb-auto-form>`'s own Shadow DOM, and `.heading`/`.p-depth`/`.bg-slate-*`
// are defined in `MedblocksAutoForm.styles` — a `css` template literal
// baked into that shadow root, using hardcoded hex colors (`#334155`,
// `#475569`, `#64748b`, `#94a3b8`, `#e2e8f0`), not the app's `--sl-color-*`
// custom properties. A page's global stylesheet can cross a shadow boundary
// through inherited properties (which is how `medblocks-overrides.css`'s
// `mb-auto-form { font-family; font-size }` rule reaches in) and through
// CSS custom properties (how the Shoelace theme tokens reach every field's
// internal `sl-*` parts) — but `.heading`'s selectors and hardcoded colors
// are neither, and ADR-0002 rules out `::part()`/shadow-piercing to reach
// them directly. So this story can't catch a `medblocks-overrides.css`
// regression the way the field stories do (there's no override surface
// here to regress) — it exists to document the current baseline and catch
// this chrome changing unexpectedly on a future medblocks-ui version bump.
//
// `<mb-auto-form>` needs a real Web Template shape (`.tree`, with `id`/
// `name`/`rmType`/`min`/`max`/`children`/`inputs` per node) rather than
// light-DOM children, so this story assigns a minimal one via the `webTemplate`
// property — the same property `CompositionForm.vue` sets on its
// `mbFormRef` — reproducing the nesting from the screenshot this story was
// written against: two top-level clusters ("Case identification",
// "Recipient", both depth 1 → `bg-slate-600`) with a nested cluster inside
// the second ("Structured name of a person", depth 2 → `bg-slate-500`).

function textField(id: string, name: string) {
  return { id, name, rmType: "DV_TEXT", min: 0, max: 1, inputs: [{ type: "TEXT" }] };
}

const WEB_TEMPLATE = {
  tree: {
    id: "consultation_report",
    name: "Consultation Report",
    rmType: "COMPOSITION",
    min: 1,
    max: 1,
    children: [
      {
        id: "case_identification",
        name: "Case identification",
        rmType: "CLUSTER",
        min: 1,
        max: 1,
        children: [
          textField("case_identifier", "Case identifier"),
          textField("case_identified", "Case identified"),
        ],
      },
      {
        id: "recipient",
        name: "Recipient",
        rmType: "CLUSTER",
        min: 1,
        max: 1,
        children: [
          {
            id: "name",
            name: "Structured name of a person",
            rmType: "CLUSTER",
            min: 1,
            max: 1,
            children: [
              textField("title", "Title"),
              textField("given_name", "Given name"),
              textField("family_name", "Family name"),
            ],
          },
        ],
      },
    ],
  },
};

const meta: Meta = {
  title: "Medblocks/Auto-Form Group Headings",
  parameters: {
    docs: {
      description: {
        component:
          "The `.heading`/`.p-depth` group-header chrome `<mb-auto-form>` generates internally for nested Web Template clusters. Baked into `mb-auto-form`'s own Shadow DOM stylesheet with hardcoded colors — not reachable by `medblocks-overrides.css` (see ADR-0002's no-`::part()` constraint). Not backed by a project Vue component (see ADR-0008).",
      },
    },
  },
  render: () => ({
    setup() {
      return { webTemplate: WEB_TEMPLATE };
    },
    template: `
      <div style="width: 480px; padding: 16px;">
        <mb-auto-form :webTemplate="webTemplate"></mb-auto-form>
      </div>
    `,
  }),
};

export default meta;
type Story = StoryObj;

export const Default: Story = {};
