import type { Meta, StoryObj } from "@storybook/vue3-vite";
import OptMetadata from "./OptMetadata.vue";

const meta: Meta<typeof OptMetadata> = {
  title: "Components/OptMetadata",
  component: OptMetadata,
  tags: ["autodocs"],
  parameters: {
    docs: {
      description: {
        component:
          "Parses the `<description>` element of a raw OPT XML string (via `DOMParser`, client-side) into author, lifecycle, purpose, and technical-metadata sections. See ADR-0021/PRD-0008.",
      },
    },
  },
};

export default meta;
type Story = StoryObj<typeof OptMetadata>;

const FULL_OPT_XML = `<?xml version="1.0" encoding="UTF-8"?>
<template>
  <description>
    <original_author id="name">Hendrik Heiser</original_author>
    <original_author id="organisation">Cistec AG</original_author>
    <original_author id="email">hendrik.heiser@cistec.com</original_author>
    <original_author id="date">2025-03-19</original_author>
    <other_contributors>Jonas Bucher (Reviewer)</other_contributors>
    <lifecycle_state>published</lifecycle_state>
    <details>
      <language><terminology_id><value>ISO_639-1</value></terminology_id><code_string>en</code_string></language>
      <purpose>Records systolic and diastolic blood pressure measurements, along with the method and body position used, for use in outpatient and inpatient encounters. Intended to be comparable across care settings and suitable for longitudinal trending.</purpose>
    </details>
    <other_details id="licence">Creative Commons Attribution-ShareAlike 4.0 International</other_details>
    <other_details id="custodian_organisation">Cistec AG</other_details>
    <other_details id="original_namespace">com.cistec</other_details>
    <other_details id="original_publisher">Cistec AG</other_details>
    <other_details id="custodian_namespace">com.cistec</other_details>
    <other_details id="MD5-CAM-1.0.1">0b1daab37a9a6d809d5dcc875960cddf</other_details>
    <other_details id="PARENT:MD5-CAM-1.0.1">005501C1FA493A483BF5F1121F2870EC</other_details>
    <other_details id="sem_ver">1.1.0</other_details>
    <other_details id="build_uid">a3f1c2e4-1234-4a5b-8c9d-1234567890ab</other_details>
    <other_details id="Generated By">Archetype Designer v1.24.16, user=4027145</other_details>
  </description>
</template>`;

const MINIMAL_OPT_XML = `<?xml version="1.0" encoding="UTF-8"?>
<template>
  <description>
    <lifecycle_state>draft</lifecycle_state>
  </description>
</template>`;

const NO_DESCRIPTION_OPT_XML = `<?xml version="1.0" encoding="UTF-8"?>
<template>
  <template_id><value>no_metadata_example</value></template_id>
</template>`;

export const Full: Story = {
  args: { optXml: FULL_OPT_XML },
};

export const MinimalMetadata: Story = {
  args: { optXml: MINIMAL_OPT_XML },
};

export const NoMetadata: Story = {
  args: { optXml: NO_DESCRIPTION_OPT_XML },
};
